version: '3'
services:
  node_expressjs_systemjs:
    container_name: node_expressjs_systemjs
    restart: always
    build:
      dockerfile: ./node-expressjs-systemjs.dockerfile
      context: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'